# ~/.config/starship.toml

# Use custom format
format = '''
$directory$rust$package[ Î» > ](fg:blue)'''



# Wait 10 milliseconds for starship to check files under the current directory.


# Disable the blank line at the start of the prompt
add_newline = false

[directory]
format = "[$path](fg:cyan)"
